services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
      - ./linux/logrotate.d/app:/etc/logrotate.d/app
    working_dir: /app
    tty: true
    environment:
      ENV: dev
    command: sh -c "go run cmd/main.go"

  db:
    image: postgres:17.4
    environment:
      POSTGRES_DB: scaf-gin_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data