services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./linux/logrotate.d/app:/etc/logrotate.d/app
    working_dir: /app
    tty: true
    command: sh -c "go run cmd/main.go"
    restart: always